### PR TITLE
Update go live content 100323

### PR DESCRIPTION
**Pull request by cirpo**

### CODE REVIEW

**Review by magnum — APPROVED** [review]
pretty ok for me and for going online today
maybe we can prevent the title to split on multiple lines with small screens, but i think we can do it later :-)

**Comment by magnum** [comment]
@cirpo you mentioned the images for socials; 
do you think we need to add og:tags in head or the default image scraped by social services' crawlers will be ok? 
cc @fgandellini 

right now fb debug says no image can be used...
Screenshot 2023-03-10 alle 11 48 01

**Comment by fgandellini** [comment]
Good point @magnum! I think it's better to add the og:tags.
I don't think it's super urgent tho, we can publish the website now, and add tags before publishing it to social media.

**Comment by magnum** [comment]
> Good point @magnum! I think it's better to add the og:tags. I don't think it's super urgent tho, we can publish the website now, and add tags before publishing it to social media.

ok for me... i'll add an issue to remember it, maybe in the future we can think about switching totally to github, pardon me DHH :-)

**Pull request merged**
