### PR TITLE
site launch

### PR DESCRIPTION
**Pull request by magnum**
see preview temporary url https://63e82e5017cc7716c3fda042--nodejsconf2023.netlify.app/
we can use netlify to share next draft versions

**useful notes for content editing**
single page `src/index.njk`
some contents managed via .md files in
```
src/includes
src/content/sponsor_packages
src/content/talks
```

**tbd**
* fixes and missing parts before going online
* steps for next releases: cfp, venue, talks etc.
* more graphics? :-) 
* choose to keep github pages (already configured) or move to netlify (useful for sharing drafts with the team + other gootd things, but it must be configured and free version allows 1 team member only, so only one user can make releases)

cc @cirpo

### CODE REVIEW

**Review by fgandellini — APPROVED** [review]
Looks great! We need to fix the WEBdeBS logo URL, and we're good to go!

About the ToDo list, here are my answers:

> fixes and missing parts before going online
> steps for next releases: cfp, venue, talks etc.

Yep, let's sync up with @cirpo about these two points.

> more graphics? :-)

I'd love to add more graphics, but I don't know where to get them.
Let's have a chat with @cirpo on this as well.

> choose to keep github pages (already configured) or move to netlify (useful for sharing drafts with the team + other gootd things, but it must be configured and free version allows 1 team member only, so only one user can make releases)

I see value in using Netlify. I'd go for that. We can find a setup so that only one user performs releases.

**Comment by magnum** [comment]
@fgandellini do you have more details about
> We need to fix the WEBdeBS logo URL
I removed the protocol because it wasn't agnostic about using http/https, but for me it's ok to keep il linked to the webdebs's website 

Let's wait notes from @cirpo 

Ok for me to use netlify, using google workspace email's routing, i setup service@webdebs.org that forwards to mime, @cirpo's an @fgandellini's gmail address so we can work with that single account but independently. 
User and password saved in the webdebs's credentials google sheet https://docs.google.com/spreadsheets/d/1tePyz3rN8ciH5_5cxtf5lXkUR78SybsjWSw9EJyKNSI/edit#gid=0
I setup a new netlify account with service@webdebs.org, and "moved" the nodejsconf2023 website to it; preview url updated above https://63e8f5e4744a8f0ba8e25d15--nodejsconf2023.netlify.app/
I'll add a basecamp todo to point dns records to the netlify endpoints...

**Comment by magnum** [comment]
webdebs logo "problem" fixed here https://github.com/WEBdeBS/nodejsconf2023/pull/4/commits/dd021199233d35ceaa9999b3b53f3c09cb9c5a23

it's related to cert problems on webdebs.org domain

Screenshot 2023-02-21 alle 14 16 46

**Comment by magnum** [comment]
@fgandellini @ceccode https://github.com/WEBdeBS/nodejsconf2023/pull/4/commits/cc1da9e6980ce1ff39616a5b633a0e1859c1192e

**Comment by fgandellini** [comment]
@magnum It looks great to me! Thanks for the fixes! :pray:

**Pull request closed without merging**
